# Prod environment
variables:

  namespace: vtpoc #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 9
  location: eastus
  environment: prod
  subscriptionId: '81abea19-79ba-4bd3-8f04-e9761df1bd23'
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-PROD-vtpoc
  ado_service_connection_aml_ws: Azure-ARM-PROD-vtpoc


  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab

  enable_aml_computecluster: "false"

  # For deployment K8 reference
  deployment_compute_target: 'aks-prod'
  deploymeny_instance_type: 'Standard_B2ms'
  deployment_instance_count: 1
  resource_limit_cpu: "100m"
  resource_limit_memory: "0.5Gi"