# Dev environment
variables:
  namespace: vtpoc #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 9
  location: centralus
  environment: dev
  subscriptionId: '3fb8bc6a-65bc-4af9-9f18-e664c908e7e7'
  enable_monitoring: true

  # Azure DevOps
  ado_service_connection_rg: DEV (3fb8bc6a-65bc-4af9-9f18-e664c908e7e7)
  ado_service_connection_aml_ws: DEV (3fb8bc6a-65bc-4af9-9f18-e664c908e7e7)

  # For pipeline reference
  resource_group: dev-usc-visittime-rg
  aml_workspace: dev-usc-visittime-mlw
  application_insights: dev-usc-visittime-mlw-ai
  key_vault: dev-usc-visittimeml-kv
  container_registry: visittime
  storage_account: devuscvisittimesa

  # For deployment K8 reference
  deployment_compute_target: 'sresharedakstest'
  deployment_instance_type: 'Standard_D4as_v5'
  deployment_instance_count: 1
  resource_limit_cpu: "100m"
  resource_limit_memory: "0.5Gi"
