# Dev environment
variables:
  namespace: vtpoc #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 9
  location: centralus
  environment: dev
  subscriptionId: '3fb8bc6a-65bc-4af9-9f18-e664c908e7e7'
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: DEV (3fb8bc6a-65bc-4af9-9f18-e664c908e7e7)
  ado_service_connection_aml_ws: dev-usc-visittime-mlw


  # For pipeline reference
  resource_group: dev-usc-visittime-rg
  aml_workspace: dev-usc-visittime-mlw
  application_insights: dev-usc-visittime-mlw-ai
  key_vault: uat-usc-infra-kv
  container_registry: visittime
  storage_account: devuscvisittimesa

  # For terraform reference
  # terraform_version: 1.5.7
  # terraform_workingdir: infrastructure
  # terraform_st_location: $(location)
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab

  enable_aml_computecluster: "false"

  # For deployment K8 reference
  deployment_compute_target: 'aks-dev'
  deployment_instance_type: 'Standard_B2ms'
  deployment_instance_count: 1
  resource_limit_cpu: "100m"
  resource_limit_memory: "0.5Gi"
