steps:
  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group create --location $(location) --name $(terraform_st_resource_group)'