steps:
  - task: TerraformTaskV2@2
    displayName: 'Terraform validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: $(System.DefaultWorkingDirectory)/$(terraform_workingdir)