name: deploy-online-endpoint-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: endpoint_name
    value: taxi-online-$(namespace)$(postfix)$(environment)

trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: DeployDev
    displayName: Create/Update Online Endpoint in Dev
    jobs:
      - job: DeployOnlineEndpointDev
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
                mkdir "mlops-templates"
          - template: ../templates/install-az-ext.yml
          - template: ../templates/install-requirements.yml
          - template: ../templates/connect-to-workspace.yml
          - template: ../templates/create-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "Taxi Online Endpoint"
              auth_mode: "key"
          - template: ../templates/create-online-deployment.yml
            parameters:
              deployment_name: taxi-online-dp
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "taxi-model@latest"
              traffic_allocation: 100
          - template: ../templates/test-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/taxi-request.json
          - template: ../templates/store_model.yml
            parameters:
              modelPath: "taxi-model@latest"
              containerName: "models"

  - stage: DeployProd
    displayName: Create/Update Online Endpoint in Prod
    dependsOn: DeployDev
    condition: succeeded('DeployDev')
    jobs:
      - job: DeployOnlineEndpointProd
        steps:
          - template: ../templates/connect-to-workspace.yml
          - template: ../templates/load_model.yml
            parameters:
              modelPath: "taxi-model@latest"
              storageAccount: "${{ variables.storage_account }}"
              containerName: "models"
          - template: ../templates/create-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "Taxi Online Endpoint"
              auth_mode: "key"
          - template: ../templates/create-online-deployment.yml
            parameters:
              deployment_name: taxi-online-dp
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "taxi-model@latest"
              traffic_allocation: 100
          - template: ../templates/test-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/taxi-request.json
