name: deploy-model-training-pipeline

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      - template: ../../config-infra-dev.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120
        steps:
          - checkout: self
            path: s/
          - task: Bash@3
            displayName: "Create checkout repository folder(s)"
            inputs:
              targetType: "inline"
              script: |
                set -e
                mkdir "$(Build.Repository.Name)"
          - template: ../templates/install-az-cli.yml
          - template: ../templates/install-requirements.yml
          - template: ../templates/connect-to-workspace.yml
          - template: ../templates/create-compute.yml
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS3_v2
              min_instances: 0
              max_instances: 1
              cluster_tier: dedicated
          - template: ../templates/register-environment.yml
            parameters:
              environment_name: taxi-train-env
              environment_description: "Training Environment for Taxi Pipeline"
              environment_path: data-science/environment/train-conda.yml
              build_type: conda
          - template: ../templates/register-data-asset.yml
            parameters:
              data_name: taxi-data
              data_description: taxi-training-dataset
              data_path: data/taxi-data.csv
              data_type: uri_file
          - template: ../templates/run-pipeline.yml
            parameters:
              pipeline_path: mlops/scripts/run_pipeline.py
              experiment_name: taxi-train-pipeline
              data_name: taxi-data
              environment_name: taxi-train-env
              compute_name: cpu-cluster
              enable_monitoring: $(enable_monitoring)
              table_name: "taximonitoring"