name: deploy-online-endpoint-pipeline

variables:
  - group: vtpoc-vg

trigger: none

resources:
  pipelines:
  - pipeline: MyBuildPipeline
    source: build
    trigger: 
      branches:
      - main
      - dev
  repositories:
  - repository: vt-ml-templates
    type: git
    name: vt-ml-templates

pool:
  vmImage: ubuntu-20.04


stages:
  - stage: DeployDev
    displayName: Create/Update Online Endpoint in Dev
    variables:
      - group: vtpoc-vg
      - template: config-infra-dev.yml@vt-ml-templates
      - name: endpoint_name
        value: vt-online-$(namespace)$(postfix)$(environment)
    jobs:
      - job: DeployOnlineEndpointDev
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'vtpoc'
              pipeline: build
              runVersion: latest
              artifactName: 'code'
          - script: |
              ls -la
              cd $(Pipeline.Workspace)/code
              ls -la
            displayName: 'Change directory to artifacts'
          - template: ../templates/connect-to-workspace.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              subscriptionId: ${{ variables.subscriptionId }}
              resource_group: ${{ variables.resource_group }}
              aml_workspace: ${{ variables.aml_workspace }}
          - template: ../templates/install-az-ext.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/install-requirements.yml
          - template: ../templates/create-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "VT Online Endpoint"
              auth_mode: "key"
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/create-online-deployment.yml
            parameters:
              deployment_name: vt-online-dp
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "vt-model@latest"
              traffic_allocation: 100
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/test-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/test-request.json
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/store_model.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '.'
              artifact: 'code'
              publishLocation: 'pipeline'

  - stage: PROD_Approval
    jobs:
      - job: CheckBranch
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Pipeline.Workspace)'
          - script: |
              cd $(Pipeline.Workspace)/code
              ls -la
              branch=$(cat branch.txt)
              echo "##vso[task.setvariable variable=branch;isOutput=true]$branch"
            displayName: 'Get branch name'
            name: setvarStep
      - job: waitForValidation
        displayName: Wait for external validation
        dependsOn: CheckBranch
        condition: and(succeeded(), eq(dependencies.CheckBranch.outputs['setvarStep.branch'], 'main'))
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              instructions: 'Please validate the PROD build configuration and resume'
              onTimeout: 'reject'


  - stage: DeployProd
    displayName: Create/Update Online Endpoint in Prod
    dependsOn: PROD_Approval
    variables:
      - group: vtpoc-vg
      - template: config-infra-prod.yml@vt-ml-templates
      - name: endpoint_name
        value: vt-online-$(namespace)$(postfix)$(environment)
    jobs:
      - job: DeployOnlineEndpointProd
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Pipeline.Workspace)'
          - script: |
              cd $(Pipeline.Workspace)/code
              ls -la
          - template: ../templates/connect-to-workspace.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              subscriptionId: ${{ variables.subscriptionId }}
              resource_group: ${{ variables.resource_group }}
              aml_workspace: ${{ variables.aml_workspace }}
          - template: ../templates/install-az-ext.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/install-requirements.yml
          - template: ../templates/register-environment.yml
            parameters:
              environment_name: vt-train-env
              environment_description: "Training and Deployment Environment for VT Pipeline"
              environment_path: data-science/environment/train-conda.yml
              build_type: conda
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'ls -la $(Pipeline.Workspace)'
          - template: ../templates/register_model.yml
            parameters:
              model_path: '$(Pipeline.Workspace)/models/vt-model/vt-model'
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/create-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "VT Online Endpoint"
              auth_mode: "key"
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/create-online-deployment.yml
            parameters:
              deployment_name: vt-online-dp
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "vt-model@latest"
              traffic_allocation: 100
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/test-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/test-request.json
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}