name: deploy-model-training-pipeline

variables:
  - group: vtpoc-vg
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../../templates-repo/config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../../templates-repo/config-infra-dev.yml

trigger:
  branches:
    include:
    - dev
    - main
  paths:
    include:
    - 'mlops/*'
    - 'data_science/*'
schedules:
- cron: "0 1 * * 1"
  displayName: Weekly build
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120
        steps:
          - checkout: self
            path: s/
          - checkout: vt-ml-templates
            path: templates-repo/
          - template: ../templates/install-az-ext.yml
          - template: ../templates/install-requirements.yml
          - template: ../templates/run-unit-tests.yml
          - template: ../templates/connect-to-workspace.yml
          - template: ../templates/import-data.yml
            parameters:
              snowflake_account: $(SNOWFLAKE_ACCOUNT)
              snowflake_user: $(SNOWFLAKE_USER)
              snowflake_password: $(SNOWFLAKE_PASSWORD)
              subscription_id: $(SUBSCRIPTION_ID)
          - template: ../templates/create-compute.yml
            parameters:
              cluster_name: cpu-cluster
              size: Standard_F4s_v2
              min_instances: 0
              max_instances: 1
              cluster_tier: dedicated
          - template: ../templates/register-environment.yml
            parameters:
              environment_name: vt-train-env
              environment_description: "Training Environment for VT Pipeline"
              environment_path: data-science/environment/train-conda.yml
              build_type: conda
          - template: ../templates/run-pipeline.yml
            parameters:
              experiment_name: vt-train-pipeline
              data_name: train
              environment_name: vt-train-env
              compute_name: cpu-cluster
              enable_monitoring: $(enable_monitoring)
              table_name: "vtmonitoring"
          - script: |
              echo $(Build.SourceBranchName) > branch.txt
            displayName: 'Write git branch to file'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'code'

