name: deploy-online-endpoint-pipeline

variables:
  - group: vtpoc-vg

trigger: none

resources:
  pipelines:
  - pipeline: MyBuildPipeline
    source: build
    trigger: 
      branches:
      - main
      - dev
  repositories:
  - repository: vt-ml-templates
    type: git
    name: vt-ml-templates

pool:
  vmImage: ubuntu-20.04


stages:
  - stage: DeployDev
    displayName: DeployDev
    variables:
      - group: vtpoc-vg
      - template: config-infra-dev.yml@vt-ml-templates
      - name: endpoint_name
        value: vt-online-$(namespace)$(postfix)$(environment)
    jobs:
      - job: DeployOnlineEndpointDev
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'vtpoc'
              pipeline: build
              runVersion: latest
              artifactName: 'code'
              targetPath: $(Pipeline.Workspace)/s
          - script: |
              echo "Contents of the s dir:"
              ls -la $(Pipeline.Workspace)/s
              branch=$(cat $(Pipeline.Workspace)/s/branch.txt)
              echo "##vso[task.setvariable variable=branch;isOutput=true]$branch"
              cd $(Pipeline.Workspace)/s/mlops/pipelines
              echo "##vso[task.setvariable variable=deployment_name;isOutput=true]vt-online-dp_$(date +%Y%m%d%H%M%S)"
            name: runBash
            displayName: 'Change directory'
          - script: |
              echo "Deployment name: $(runBash.deployment_name)"
            displayName: 'Print deployment name'
          - template: ../templates/connect-to-workspace.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              subscriptionId: ${{ variables.subscriptionId }}
              resource_group: ${{ variables.resource_group }}
              aml_workspace: ${{ variables.aml_workspace }}
          - template: ../templates/install-az-ext.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/install-requirements.yml
#          - template: ../templates/create-online-endpoint.yml
#            parameters:
#              endpoint_name: "${{ variables.endpoint_name }}"
#              endpoint_description: "VT Online Endpoint"
#              auth_mode: "key"
#              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
#              deployment_compute_target: "${{ variables.deployment_compute_target }}"
#          - template: ../templates/create-online-deployment.yml
#            parameters:
#              deployment_name: $(runBash.deployment_name)
#              endpoint_name: "${{ variables.endpoint_name }}"
#              model_path: "vt-model@latest"
#              traffic_allocation: 100
#              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
#              instance_type: "${{ variables.deploymeny_instance_type }}"
#              instance_count: "${{ variables.deployment_instance_count }}"
#              resource_limit_cpu: "${{ variables.resource_limit_cpu }}"
#              resource_limit_memory: "${{ variables.resource_limit_memory }}"
#          - template: ../templates/test-online-endpoint.yml
#            parameters:
#              endpoint_name: "${{ variables.endpoint_name }}"
#              sample_request: 'data/test-request.json'
#              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/store_model.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)/s'
              artifact: 'code'
              publishLocation: 'pipeline'

  - stage: PROD_Approval
    dependsOn:
    - DeployDev
    condition: and(succeeded('DeployDev'), eq(dependencies.DeployDev.outputs['DeployOnlineEndpointDev.runBash.branch'], 'main'))
    jobs:
      - job: waitForValidation
        displayName: Wait for external validation
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              instructions: 'Please validate the PROD build configuration and resume'
              onTimeout: 'reject'


  - stage: DeployProd
    displayName: DeployProd
    dependsOn: 
      - PROD_Approval
      - DeployDev
    condition: succeeded('PROD_Approval')
    variables:
    - group: vtpoc-vg
    - template: config-infra-prod.yml@vt-ml-templates
    - name: endpoint_name
      value: vt-online-$(namespace)$(postfix)$(environment)
    - name: deployment_name
      value: "$[stageDependencies.DeployDev.DeployOnlineEndpointDev.outputs['runBash.deployment_name']]"
    jobs:
      - job: DeployOnlineEndpointProd
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'code'
              targetPath: '$(Pipeline.Workspace)/s'
          - script: |
              echo "Contents of s dir:"
              cd $(Pipeline.Workspace)/s/mlops/pipelines
          - template: ../templates/connect-to-workspace.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              subscriptionId: ${{ variables.subscriptionId }}
              resource_group: ${{ variables.resource_group }}
              aml_workspace: ${{ variables.aml_workspace }}
          - template: ../templates/install-az-ext.yml
            parameters:
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/install-requirements.yml
          - template: ../templates/register-environment.yml
            parameters:
              environment_name: vt-train-env
              environment_description: "Training and Deployment Environment for VT Pipeline"
              environment_path: data-science/environment/train-conda.yml
              build_type: conda
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'ls -la $(Pipeline.Workspace)/s'
          - template: ../templates/register_model.yml
            parameters:
              model_path: 'models/vt-model/vt-model'
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
          - template: ../templates/create-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              endpoint_description: "VT Online Endpoint"
              auth_mode: "key"
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              deployment_compute_target: "${{ variables.deployment_compute_target }}"
          - template: ../templates/create-online-deployment.yml
            parameters:
              deployment_name: "${{ variables.deployment_name }}"
              endpoint_name: "${{ variables.endpoint_name }}"
              model_path: "vt-model@latest"
              traffic_allocation: 100
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}
              instance_type: "${{ variables.deploymeny_instance_type }}"
              instance_count: "${{ variables.deployment_instance_count }}"
              resource_limit_cpu: "${{ variables.resource_limit_cpu }}"
              resource_limit_memory: "${{ variables.resource_limit_memory }}"
          - template: ../templates/test-online-endpoint.yml
            parameters:
              endpoint_name: "${{ variables.endpoint_name }}"
              sample_request: data/test-request.json
              ado_service_connection_aml_ws: ${{ variables.ado_service_connection_aml_ws }}