parameters:
- name: endpoint_name
  type: string
- name: deployment_name
  type: string
- name: model_path
  type: string
- name: traffic_allocation
- name: ado_service_connection_aml_ws
  type: string

steps:
    
- task: AzureCLI@2
  displayName: Creating online deployment
  inputs:
    azureSubscription: ${{ parameters.ado_service_connection_aml_ws }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -x
      python $(Pipeline.Workspace)/mlops/scripts/create_online_deployment.py \
        --endpoint_name "${{parameters.endpoint_name}}" \
        --deployment_name "${{parameters.deployment_name}}" \
        --model_path "${{parameters.model_path}}" \
        --traffic_allocation "${{parameters.traffic_allocation}}" \
        --scoring_script_dir "$(Pipeline.Workspace)/mlops/scripts/"


