channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - pandas==2.2.0
  - psutil==5.9.8
  - scikit-learn==1.4.1.post1
  - typing-extensions==4.9.0
  - xgboost==2.0.3
name: mlflow-env
