channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-mlflow
      - azure-ai-ml
      - pyarrow
      - scikit-learn
      - pandas
      - joblib
      - matplotlib
      - azureml-inference-server-http
      - snowflake-connector-python
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector